apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - config-bundle-secret.yaml

patchesStrategicMerge:
  - quay-registry-patch.yaml

commonLabels:
  environment: production
  app.kubernetes.io/managed-by: argocd
