apiVersion: v1
kind: Namespace
metadata:
  name: quay-enterprise
  labels:
    app.kubernetes.io/part-of: quay
    # Habilita monitoreo del namespace por Prometheus
    openshift.io/cluster-monitoring: "true"
